### ISSUE TITLE
Implementar uma stream de dados para listar os cards

### ISSUE THREAD

**Issue by cherryramatisdev** [cherryramatisdev/4noobs_tracker#10]
Hoje nós apenas fazemos um `Repository.all` e listamos na pagina normalmente, mas isso causa um efeito bem estranho onde o usuário fica alguns segundos com a tela em branco ate poder ver alguns cards sendo mostrados, por conta disso seria incrível ter uma implementação de stream de dados:

Um exemplo de stream de dados no controller:

```ruby
class RepositoriesController < ApplicationController
  include ActionController::Live

  def index
    response.headers['Content-Type'] = 'text/event-stream'

    Repository.find_each(batch_size: 100) do |repository|
      response.stream.write(render_to_string(partial: 'repository', locals: { repository: repository }))
    end
  ensure
    response.stream.close
  end
end
```

Nesse caso estamos esperando a existência de uma partial em `app/views/repository/_repository.html.erb`

**Comment by Nandosts** [comment]
Cherry, tava tentando mexer nessa feature, mas honestamente, stream de dados é beeem complexo kk
E ela ainda tenta ser um negoço contínuo... ou seja, sempre estar atualizando 

Você se importa se eu subir um PR pra solução alternativa, e vc dar uma olhada pra a gente?

Consiste em:

- Usar uma gem de paginação para carregar de 10 em 10 itens, o que resolve o problema de renderizar todos de uma só vez;
- Criar uma tela de loading por padrão, para ter algo na tela quando tiver algo pesado ao invés de piscar em branco;
- Mover o cdn do unocss para um arquivo importável, ao invés do link. Assim ele fica em um arquivo fixo no projeto, ao invés de ter que ser baixado na tag <script> (Que eu suponho que talvez cause um pouco da demora também)

Desculpa se eu tiver fazendo ou falando alguma besteira kk, só fui pensando que na vdd uma otimização ou outra dessas podem dar uma ajuda

**Comment by cherryramatisdev** [comment]
Analise muito foda! pode sim fique a vontade
