### ISSUE TITLE
Complementar links do card

### ISSUE THREAD

**Issue by cherryramatisdev** [cherryramatisdev/4noobs_tracker#12]
# Introdução

Optamos por adicionar mais alguns links de ajuda para facilitar a navegação pelos repositórios do 4noobs, portanto precisamos incluir no "footer" do card mais alguns links de navegação:

| Atualmente (no site) | Melhorado (Figma) |
|---------------------|--------------------|
| <img width="277" alt="image" src="https://github.com/cherryramatisdev/4noobs_tracker/assets/86631177/368e3679-f578-4636-aea3-da9339d0cb19"> | <img width="343" alt="image" src="https://github.com/cherryramatisdev/4noobs_tracker/assets/86631177/37d88ca2-8ffd-4545-b7eb-35ce39d2ebb3"> |
| N/A | [Figma Link](https://www.figma.com/file/o7gk90f1skJQRlgNFiEQFI/Proposta-4Noobs-Tracker?type=design&node-id=15-60&mode=dev) |

O formato dessas urls vai seguir o seguinte:

- *Ver todas as issues*: `https://github.com/<OWNER>/<NAME>/issues`
- *Ver todos os PRs*: `https://github.com/<OWNER>/<NAME>/pulls`

# Contexto

Arquivo para editar: https://github.com/cherryramatisdev/4noobs_tracker/blob/main/app/views/repository/_card.html.erb

Hoje tanto a informação de **owner** quanto de **name** existem na tabela de "repository", portanto o link vai se tornar algo como:

```erb
<a href="https://github.com/<%= repository.owner %>/<%= repository.name %>/issues">Ver todas as issues</a>
```

**Comment by harkato** [comment]
Gostaria de trabalhar nessa issue!

**Comment by cherryramatisdev** [comment]
Vai que eh tua @harkato
