### ISSUE TITLE
Definir uma altura máxima ou fixa para os cards

### ISSUE THREAD

**Issue by Nandosts** [cherryramatisdev/4noobs_tracker#18]
## Problema

Ao realizar testes relacionados aos cards, observei que o visual se comportou de maneira satisfatória, mesmo quando havia um grande número de issues associadas a um projeto. No entanto, percebi que, à medida que o número de issues aumenta, os cards também crescem indefinidamente em altura.

## Solução Proposta

Sugiro que implementemos um controle de tamanho para os cards e apliquemos uma propriedade `overflow-y: auto` à div que contém as issues. Isso garantiria que, quando houver um grande volume de issues, uma barra de rolagem seja criada na div, em vez de permitir que o card cresça indefinidamente. Isso ajudaria a manter a consistência visual e a usabilidade do sistema, mesmo em projetos muito movimentados.

## Exemplo

![Exemplo do problema](https://github.com/cherryramatisdev/4noobs_tracker/assets/65089035/ca040c83-ef15-442c-97c9-d3e6b95e3d39)

## Tarefas

- [ ] Implementar limite de altura para os cards.
- [ ] Aplicar a propriedade `overflow-y: auto` à div das issues.
- [ ] Testar o comportamento em projetos com um grande número de issues.
- [ ] Garantir que a alteração não afete negativamente a usabilidade em projetos menos movimentados.

**Comment by cherryramatisdev** [comment]
Seria bem interessante saber como fica a tela com a scrollbar ativada e talvez entender se podemos estilizar a scrollbar para nao causar uma divergência muito grande entre o card sem scroll e com scroll

**Comment by willy-r** [comment]
@cherryramatisdev mockei algumas coisas e fiz alguns testes para verificar o visual de como ficaria com a scrollbar ativada, inclusive levando em consideração os melhoramentos que estão no Figma em relação aos links no footer, esse foi o resultado:
![image](https://github.com/cherryramatisdev/4noobs_tracker/assets/47596121/ce0d747a-ebbb-4722-956a-923135733691)

**Comment by cherryramatisdev** [comment]
Acho que pra uma primeira versao eh bem ok viu, talvez possamos pensar em estilizar essa scrollbar no futuro

mas ta bem de boa honestamente

Se quiser tocar essa PR fique a vontade

**Comment by willy-r** [comment]
Vou ficar com esse PR então, aproveitar e estudar em estilizar a scrollbar pra ver como fica.

Eu pensei em não mudar muito, talvez só deixar mais fina para o texto da issue/pr caber mais na linha, e talvez a cor da scrollbar. Mas acho que esse cinza também já ficaria bom.

**Comment by willy-r** [comment]
Como disse anteriormente eu pensei em algo mais ou menos assim para a estilização:

| Na cor cinza | Na cor roxa | Navegadores testados |
| ---------------------- | ---------------------- | ---------------------- |
| ![image](https://github.com/cherryramatisdev/4noobs_tracker/assets/47596121/788db4ac-f5e3-408e-9f41-192de103dc32) | ![image](https://github.com/cherryramatisdev/4noobs_tracker/assets/47596121/41808a20-c815-489e-bef7-a7627d79d1f4) | Chrome |

Estou utilizando [esse artigo](https://css-tricks.com/the-current-state-of-styling-scrollbars-in-css/) para referências, de acordo com eles esse exemplo funcionaria perfeitamente para Chrome, Safari, e Firefox.
