### ISSUE TITLE
Proposta inicial de UI

### ISSUE THREAD

**Issue by cherryramatisdev** [cherryramatisdev/4noobs_tracker#3]
# Descrição

Hoje temos uma UI super básica onde temos uma lista de card em coluna como mostrado abaixo:

![image](https://github.com/cherryramatisdev/4noobs_tracker/assets/86631177/271eb630-2010-41da-a7ac-9a10a4ea1007)

Eu acredito que podemos bolar uma UI onde abusamos mais de um layout compacto com grid e onde cada card mostra menos texto e mais ícones para facilitar navegação

> Disclaimer: Não sou uma pessoa de UI então qualquer proposta sera avaliada e discutida por todas as pessoas envolvidas no repositório.

# O que consideramos como uma proposta valida

Um link para o figma com alguma proposta de layout tanto para a lista quanto para o card individual

**Comment by cherryramatisdev** [comment]
A partir daqui podemos criar mais issues relacionadas ao frontend

**Comment by Nandosts** [comment]
Booa noite Cherry
Olha, faz um tempo que eu não mexo com figma, pra ser sincero, e não sou de UI também

Mas eu tava tentando dar uma mexida, você quer um card que nem o do trello mais ou menos?

Tava fazendo algo parecido com o que já tem na página da 4noobs, mas não sei se vai encaixar, se você quiser algo mais curtinho, menor...
Desculpa também se a tentativa for muito falha, até amanhã vou ter mais inspiração, claro, hoje fiz mais é coletar as corezinhas e brincar um pouquinho kk

Essa foi uma primeira versão que testei

![image](https://github.com/cherryramatisdev/4noobs_tracker/assets/65089035/c165adba-72ba-428d-a0c6-6d4f8d9c525a)

**Comment by cherryramatisdev** [comment]
Oi nando tudo bom? primeiramente muito obrigada pela contribuição <3 

A unica ideia que eu tava pensando inicialmente é cobrir menos espaço sabe? Hoje temos 48 repositorios e isso pode crescer bastante com o tempo (sem falar do numero de issues)

Então a principio eu gostaria de ser capaz de fazer um grid ao inves de fazer uma coluna gigantona, curti demais a sua proposta, tenho só alguns comentarios nela:

1. A interação principal do card vai ser abrir as issues e pull requests, então seria legal ter um destaque também para acessar cada issue
2. Imagino que vc colocou para testar, mas não acredito que temos utilidade para a foto, tirando ela acredito que ganhamos espaço inclusive
3. Para titulos grandes de issue, talvez vamos precisar colocar `...`, a maioria dos titulos de issue acabam sendo bem grandes

**Comment by amdfd** [comment]
Considerando a proposta de layout do @Nandosts e as considerações da @cherryramatisdev, pensei na seguinte proposta:

![image](https://github.com/cherryramatisdev/4noobs_tracker/assets/65048587/cacc7f5d-004a-4f09-82f9-461b013e57af)

- Uso dos ícones de pull request e de issue em vez das tags para indicar o tipo de conteúdo
- Uso das tags para indicar status do conteúdo

Ainda estou pensando em uma forma de separar melhor visualmente o título do conteúdo e de adicionar alguma imagem ou ícone que facilite o reconhecimento do repositório (talvez adicionar o ícone da linguagem ou ferramenta pertinente ao 4Noobs?). O que acham?

[Link do Figma ](https://www.figma.com/file/o7gk90f1skJQRlgNFiEQFI/Proposta-4Noobs-Tracker?type=design&node-id=0%3A1&mode=design&t=ZCHyXgsgb6K6ZNln-1)

**Comment by cherryramatisdev** [comment]
Sobre o ícone de linguagem, eh bem possível com o que temos hoje, mas iriamos precisar ter um ícone "fallback" caso não consigamos achar nenhum match (por exemplo, para o LPI4noobs)

No mais gostei mto da proposta, por mim podemos seguir com isso para uma primeira versão honestamente

**Comment by Lorenalgm** [comment]
Ficou bem legal! 
Uma dúvida, vai exibir todas as PRs abertas ou vai exibir no máximo 3 por padrão e um linkzinho tipo `Ver mais 5 PRs em aberto`

**Comment by cherryramatisdev** [comment]
Então, hoje não é um problema listar tudo pq temos 35 issues/pr no total pra todos os repositórios

mas se a gente começar a ter muito mais tração, precisamos mostrar uma parte com "ver mais" mesmo 

N tem problema discutir pra fazer isso agora, eu só não fiz por preguiça mesmo kkkk

**Comment by amdfd** [comment]
Sugestão de design com ícones das linguagens e ícone fallback, e adição dos links "ver mais" para PRs e issues quando houver mais de 3 itens por card:

![image](https://github.com/cherryramatisdev/4noobs_tracker/assets/65048587/86d705e0-3c44-40a6-94b7-b4cfc5c92725)

Ainda estou pensando em como deixar o topo dos cards menos vazios 🤔 

[Link do Figma](https://www.figma.com/file/o7gk90f1skJQRlgNFiEQFI/Proposta-4Noobs-Tracker?type=design&node-id=0%3A1&mode=design&t=sucUrvidcUB5pg7U-1)

**Comment by cherryramatisdev** [comment]
talvez a gente consiga colocar o ícone da linguagem perto no topo dos  cards? talvez resolveria a situação de preencher conteudo

Acho que mais respiro pros links no footer do card funciona bem tbm

**Comment by cherryramatisdev** [comment]
Na PR da issue #6 consegui implementar a ultima proposta do card, por hora vou fechar essa issue por termos uma versão inicial

Mas podemos criar outra issue para possíveis melhorias ou reabrir essa caso necessário.
