### ISSUE TITLE
Adicionar nova coluna na tabela de Repository

### ISSUE THREAD

**Issue by willy-r** [cherryramatisdev/4noobs_tracker#33]
# Introdução

Como descrito na issue #11, foi proposta uma ideia para adição de uma **badge** no card dos repositórios representando a linguagem de programação daquele repositório ou no caso do repositório não estar relacionado com uma linguagem de programação, utilizar uma imagem default.

Essa issue tem como objetivo sugerir uma forma de implementação, utilizando [devicon](https://github.com/devicons/devicon/).

## De onde vem as informações dos repositórios?

As informações são parseadas aqui:
https://github.com/cherryramatisdev/4noobs_tracker/blob/3fe5754f4ae96cccfa9e9d60b53609c06a8210e5/app/services/github/extract_repositories.rb#L6-L11

Basicamente, ele acessa o raw do `README.md` da [4Noobs](https://github.com/he4rt/4noobs) e extrai os links de todas as linhas das tabelas. Através do link ele coleta informações como: o **dono do repositório**, o **nome do repositório** e a **url**  em si e depois isso é salvo no banco de dados.

## Implementação

Para essa implementação destaca-se os seguintes passos:
1. Criar uma nova coluna na tabela de **Repository**, que pode se chamar `technology` e será uma string que poderá aceitar `NULL`
2. Criar uma nova coluna na tabela de **Repository**, que pode se chamar `technology_image_pattern` e será uma string que poderá aceitar `NULL`
3. Buscar as tecnologias, ou melhor, os nomes relacionados aos repositórios como no exemplo:
    ![image](https://github.com/cherryramatisdev/4noobs_tracker/assets/47596121/ba08992e-1597-4c3d-a9b8-d598b51a874d)
4. Salvar essa informação no banco de dados
5. Criar um método para padronizar os nomes para a imagem da tecnologia em questão (se existir), por exemplo se a tech for **C#**, deverá ser transformado para **csharp**, com tudo minúsculo, sem caracteres especiais e sem espaços.
6. Salvar essa informação no banco de dados
8. No layout, usar a imagem salva em `/assets/images` seguindo o padrão que está na coluna `technology_image_pattern` correspondente ao repositório.
9. Como imagem fallback, para o caso da URL não ser achada com a tecnologia fornecida, teria como fazer o seguinte:
    ```erb
    <img
      src="<%= '/assets/' + technology_image_pattern + '.svg' %>"
      alt="<%= 'Card of the repository ' + technology %>"
      width="23"
      onerror="this.onerror=null; this.src='/assets/default.svg'; this.alt='Card of the repository default'"
    >
    ```

## Mapeamento dos ícones que existem no devicon

Tabela contendo os padrões de linguagem de programação no repo do 4Noobs e seu equivalente no Devicon:

| [4Noobs](https://github.com/he4rt/4noobs) | [Devicon](https://github.com/devicons/devicon/tree/master/icons) | Padrão da imagem | Caso especial?
| --- | --- | --- | --- |
| Bash | bash | bash |
| C | c | c |
| C++ | cplusplus | cplusplus | ✅ |
| C# | csharp | csharp | ✅ |
| Crystal | crystal | crystal |
| CSS | css3 | css |
| Dart | dart | dart |
| Elixir | elixir | elixir |
| Go | go | go |
| HTML | html5 | html |
| Java | java | java |
| JavaScript | javascript | javascript |
| Markdown | markdown | markdown |
| OCaml | ocaml | ocaml |
| PHP | php | php |
| Python | python | python |
| Rust | rust | rust |
| Ruby | ruby | ruby |
| Swift | swift | swift |
| TypeScript | typescript | typescript |
| Kotlin | kotlin | kotlin |
| Angular | angularjs | angular |
| NextJS | nextjs | nextjs |
| Vue | vuejs | vue |
| Flutter | flutter | flutter |
| Django | django | django |
| Spring | spring | spring |
| Git | git | git |
| Vim | vim | vim |
| Linux | linux | linux |
| MySQL | mysql | mysql |
| MongoDB | mongodb | mongodb |
| PostgreSQL | postgresql | postgresql |
| Haskell | haskell | haskell |
| R | r | r

## Conclusão

Peço perdão antes de mais nada se me estendi demais, ainda tô aprendendo a definir requisitos, aceito sugestões dessa implementação principalmente em como identificar se a tecnologia existe ou não para mostrar o ícone do **devicon** ou o default.

**Comment by cherryramatisdev** [comment]
Perfeito, uma unica coisa que eu adicionaria na listagem dos requisitos é criar uma classe  para sanitizar a string, removendo unicode, espaços em branco, deixando tudo em lowercase, etc etc etc...

De resto, concordo completamente!

**Comment by willy-r** [comment]
Oi cherry! Muito obrigado pela sugestão, irei adicionar esse passo na ideia de implementação também.

**Comment by willy-r** [comment]
A implementação sugerida teve uma pequena mudança, pois não estava dando certo buscar as imagens direto da CDN da Devicon, estava tornando a implementação muito engessada, e a intenção era o contrário, facilitar a implementação e tornar escalável.

Com isso, tive a ideia de mapear todas as tecnologias dos 4Noobs e buscar direto no repo do Devicon cada um dos ícones, que era a ideia original de usar os assets e a gente mesmo servir. Creio que possa ser uma boa solução por agora, porém teremos sempre que verificar se o ícone para 4Noobs futuros existem, e baixar no repo com o padrão do nome do 4Noobs.

Atualizei a documentação de implementação para esse caso.

**Comment by cherryramatisdev** [comment]
@willy-r Concordo plenamente com a implementacao, acho que fica mais facil controlar as imagens que queremos no projeto ja que podemos desenhar novas no figma caso necessario

Boa!
