### ISSUE TITLE
Configurar um cron job para executar o comando de fetch:issues

### ISSUE THREAD

**Issue by cherryramatisdev** [cherryramatisdev/4noobs_tracker#7]
O comando `rails fetch:issues` tem como objetivo procurar todas as issues de todos os repositórios cadastrados via API do github.

A principio esse comando precisa executar 1 vez por dia, caso a movimentação aumente nos 4noobs podemos revisar essa regra.

**Comment by Nandosts** [comment]
Boa tarde, tenho interesse em catar a issue hahah

**Comment by cherryramatisdev** [comment]
Ta na mão primo! brilha
